# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-03-16 01:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='qiushi_joke',
            table='qiushi_joke',
        ),
    ]
